Add CoreML sample
hacarus/CoreMLSample pull request #1
Opened 2018-07-03 10:38 UTC by tomoyamatsuyama

### 概要
2画面構成です。

- MLModelList
  - ML Modelを選択する画面です。
  - 使いたいML Modelをproject内に追加してViewModelのenumで宣言することで使えます  

- AVCapture
  - 前画面で選択したML Modelを用いて画像解析を行います。

### reviewして欲しいところ
- AVCaptureViewController.swiftのsetUpAVCapture()の書き方がおかしくないか。
- CoreMLの使い方が正しいか。

### Demo
![demo](https://user-images.githubusercontent.com/30315659/42215198-abfc8e62-7ef8-11e8-8eac-38bf14f02526.gif)

2018-07-04 01:31 UTC, tomoyamatsuyama commented
@tomokitakahashi 
Reviewお願いします。

2018-07-08 01:28 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +        textLayer = CATextLayer()
config周りはなるべく`lazy var`つかってクロージャの中に書いたらスッキリするかね

2018-07-08 01:32 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +        textLayer = CATextLayer()
```swift
    private lazy var textLayer: CATextLayer = {
        let layer = CATextLayer()
        // configure
        return layer
    }()
```

2018-07-08 01:37 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AppDelegate.swift
> +        self.window = UIWindow(frame: UIScreen.main.bounds)
frame不要

```swift
self.window = UIWindow()
```

2018-07-08 01:39 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +                print(error)
せめてprintは手元だけにしようか、NSLogに

2018-07-08 01:41 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +            for text in classification.identifier {
reduce使えるはず

2018-07-08 01:43 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +        return VNCoreMLRequest(model: model, completionHandler: self.handleModel)
```swift
return  .init(model: model, completionHandler: self.handleModel)
```

2018-07-10 02:34 UTC, tomoyamatsuyama commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +        textLayer = CATextLayer()
そうですね。layerで分けます！

2018-07-10 02:35 UTC, tomoyamatsuyama commented on CoreMLSample/CoreMLSample/AppDelegate.swift
> +        self.window = UIWindow(frame: UIScreen.main.bounds)
なるほど！

2018-07-10 02:36 UTC, tomoyamatsuyama commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +                print(error)
はい。m(_ _)m

2018-07-10 03:51 UTC, tomoyamatsuyama commented
@tomokitakahashi 
修正したので確認お願いします。

2018-07-10 08:21 UTC, tomoyamatsuyama commented
### 変更点
`MLModelListViewController.swift`から、`AVCaptureViewController` に遷移する時に選択したセルでcase文で`MLModel`を作成していたが、`MLModels`のプロパティとしてmodelを定義しました。

2018-07-17 04:54 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +    private var viewModel: AVCaptureViewModel!
`inject`でviewModelをsetする必要ある？
initにしてviewModelのOptional消した方がよさげ

2018-07-17 04:56 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +final class AVCaptureViewController: UIViewController, AVCaptureVideoDataOutputSampleBufferDelegate {
サブクラスにAV~つけたらAVFoundationのものとややこしいのでAV不要

2018-07-17 04:59 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +    private lazy var captureSession: AVCaptureSession = {
AVCaptureSessionはlazy varにしないほうがよさそうinput/ outputの処理まで中に書いてしまっててややこしい

2018-07-17 05:00 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +        output.setSampleBufferDelegate(self, queue: DispatchQueue.init(label: "video"))
```swift
output.setSampleBufferDelegate(self, queue: .init(label: "video"))
```

2018-07-17 05:01 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +    private lazy var detectLayer: CALayer = {
なぜプロパティがメソッドの下に記述されている？injectより上に書くべき

2018-07-17 05:01 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSample/AVCapture/AVCaptureViewController.swift
> +    lazy var modelRequest: VNCoreMLRequest = {
これも

2018-07-17 05:03 UTC, tomokitakahashi commented on CoreMLSample/CoreMLSampleTests/CoreMLSampleTests.swift
> +//
テスト書かないなら消して

2018-07-17 05:07 UTC, tomosaaan requested changes
コメントの他にREADME.mdを英語で書くこと

2018-07-24 06:36 UTC, merged